import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header/Header";
import { AuthProvider, useAuth } from "./context/authcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TODOs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
